# Generated by Django 3.0.6 on 2020-05-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_Software',
            new_name='Files',
        ),
    ]
