# Generated by Django 3.0.6 on 2020-05-25 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_book', '0002_auto_20200525_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='os_name',
        ),
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='counter_download',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
