# Generated by Django 3.0.6 on 2020-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0005_auto_20200526_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='countercomment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
