# Generated by Django 3.0.6 on 2020-05-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0006_book_countercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='user',
        ),
    ]
