# Generated by Django 3.0.6 on 2020-05-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0007_remove_files_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_book.Book'),
        ),
    ]
