# Generated by Django 3.0.6 on 2020-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0009_auto_20200530_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='title_link',
            field=models.CharField(default='لینک دانلود', max_length=100, null=True),
        ),
    ]
