# Generated by Django 3.0.6 on 2020-05-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0010_auto_20200530_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='adminresult',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
