# Generated by Django 3.0.6 on 2020-06-02 09:39

import app_book.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0011_auto_20200531_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to=app_book.models.file_path)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('publish', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True)),
            ],
        ),
    ]
