# Generated by Django 3.0.6 on 2020-06-02 13:05

import app_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0012_blogbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster_sugest',
            field=models.ImageField(null=True, upload_to=app_book.models.image_path),
        ),
        migrations.AddField(
            model_name='book',
            name='sugest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogbook',
            name='image',
            field=models.ImageField(null=True, upload_to=app_book.models.imageblog_path),
        ),
    ]
