# Generated by Django 3.0.6 on 2020-06-04 07:42

import app_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0013_auto_20200602_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='poster_sugest',
            field=models.ImageField(blank=True, null=True, upload_to=app_book.models.image_path),
        ),
    ]
