# Generated by Django 3.0.5 on 2020-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='counter_download',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='system_requirment',
            field=models.TextField(null=True),
        ),
    ]
