# Generated by Django 3.0.5 on 2020-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0002_auto_20200430_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True),
        ),
    ]
