# Generated by Django 3.0.5 on 2020-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0003_auto_20200501_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='tutorial_install',
            field=models.TextField(null=True),
        ),
    ]
