# Generated by Django 3.0.5 on 2020-05-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0005_auto_20200502_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_link',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
