# Generated by Django 3.0.5 on 2020-05-02 10:58

import app_software.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0007_auto_20200502_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=app_software.models.file_path)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_software.Software')),
            ],
        ),
        migrations.DeleteModel(
            name='Download_Link',
        ),
    ]
