# Generated by Django 3.0.5 on 2020-05-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0008_auto_20200502_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_software',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True),
        ),
    ]
