# Generated by Django 3.0.5 on 2020-05-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0009_file_software_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_software',
            name='title_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
