# Generated by Django 3.0.6 on 2020-05-07 09:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0012_auto_20200507_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='system_requirment',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='tutorial_install',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
