# Generated by Django 3.0.6 on 2020-05-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0013_auto_20200507_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='suggest',
            field=models.BooleanField(default=False),
        ),
    ]
