# Generated by Django 3.0.6 on 2020-05-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0014_software_suggest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='counter_view',
        ),
    ]
