# Generated by Django 3.0.6 on 2020-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0015_remove_software_counter_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_software',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
