# Generated by Django 3.0.6 on 2020-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0017_software_counterlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='countercomment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
