# Generated by Django 3.0.6 on 2020-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0019_software_updatedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_software',
            name='title_link',
            field=models.CharField(default='لینک دانلود', max_length=100, null=True),
        ),
    ]
