# Generated by Django 3.0.6 on 2020-05-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
