# Generated by Django 3.0.6 on 2020-05-12 14:52

import app_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_auto_20200512_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app_account.models.image_path),
        ),
    ]
