# Generated by Django 3.0.6 on 2020-05-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0008_softrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='softrequest',
            name='adminresult',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softrequest',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='softrequest',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
