# Generated by Django 3.0.6 on 2020-05-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0005_auto_20200511_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumment',
            name='validation',
            field=models.BooleanField(choices=[(False, 'ایید شده'), (True, 'تایید نشده')], default=False, null=True),
        ),
    ]
