# Generated by Django 3.0.6 on 2020-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0006_cumment_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumment',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
