# Generated by Django 3.0.6 on 2020-05-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0007_auto_20200512_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_social.Cumment'),
        ),
    ]
