# Generated by Django 3.0.6 on 2020-05-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app_social', '0009_cumment_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumment',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='cumment',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='cumment',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
