# Generated by Django 3.0.6 on 2020-05-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0010_auto_20200519_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='counterlike',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
