# Generated by Django 3.0.6 on 2020-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0011_like_counterlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='counterlike',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
