# Generated by Django 3.0.6 on 2020-05-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0012_auto_20200522_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='counterlike',
        ),
    ]
